=server:
  port: 8080   # Puerto del Gateway

spring:
  application:
    name: gateway

  datasource:
    url: jdbc:mysql://localhost:3308/auth?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    compatibility-verifier:
      enabled: false

    gateway:
      routes:

        # --- Usuario MS ---
        - id: usuario-ms
          uri: http://localhost:8001
          predicates:
            - Path=/usuarios/**, /cuentas/**

        # --- Monopatin MS ---
        - id: monopatin-ms
          uri: http://localhost:8006
          predicates:
            - Path=/monopatines/**

        # --- Parada MS ---
        - id: parada-ms
          uri: http://localhost:8005
          predicates:
            - Path=/paradas/**

        # --- Tarifa MS ---
        - id: tarifa-ms
          uri: http://localhost:8004
          predicates:
            - Path=/tarifas/**

        # --- Viaje MS ---
        - id: viaje-ms
          uri: http://localhost:8007
          predicates:
            - Path=/viajes/**

        # --- Factura MS ---
        - id: factura-ms
          uri: http://localhost:8003
          predicates:
            - Path=/facturas/**


app:
  jwt:
    secret: "N7f3Qp92LmA1zX8kB4rT6yWc9Vh2Jq5S"
    token-validity-in-seconds: 86400   # 24 horas


logging:
  level:
    org.springframework.security: INFO
    org.springframework.cloud.gateway: INFO
