services:
  parada-db:
    image: mysql:8.3.0
    container_name: parada-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: parada
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3309:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "user", "-puser"]
      interval: 10s
      timeout: 5s
      retries: 5

  usuario-db:
    image: mysql:8.0
    container_name: usuario-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usuario
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3310:3306"

  cuenta-db:
    image: mysql:8.0
    container_name: cuenta-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cuenta
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3311:3306"

networks:
  app-network:
    driver: bridge


