services:
  parada-db:
    image: mysql:8.3.0
    container_name: parada-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: parada
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3309:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-puser"]
      interval: 10s
      timeout: 5s
      retries: 5

  monopatin-db:
    image: mongo:6.0
    container_name: monopatin-db
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo_data:/data/db

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  mongo_data:
